# Generated by Django 6.0.3 on 2026-03-31 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generador', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=25)),
                ('numero_serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horometro', models.IntegerField()),
                ('fecha_ultimo_mantenimiento', models.DateField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.componente')),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.generador')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.generador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horometro', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('descripcion', models.CharField(max_length=500)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.componente')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.mantenimientogenerador')),
            ],
        ),
        migrations.AddField(
            model_name='generador',
            name='tipo_uso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.tipousogenerador'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.rol')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimientogenerador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyMGeneradoresWeb.usuario'),
        ),
    ]
